version: '3.8'

services:
  nats:
    image: nats:2.12.2-alpine3.22
    container_name: nats
    command: -V -D -js -sd /data -m 8222
    ports:
      - "4222:4222"
      - "8222:8222"
      - "6222:6222"
    stdin_open: true
    tty: true
    volumes:
      - nats_data:/data
    healthcheck:
      test: wget http://localhost:8222/healthz -q -S -O -
      interval: 5s
      timeout: 3s
      retries: 3

  runner:
    build: .
    depends_on:
      nats:
        condition: service_healthy
    environment:
      - NATS_URL=nats://nats:4222
    restart: always
    deploy:
      replicas: 3

volumes:
  nats_data:
